services:
  tiktokmonitor-server:
    build:
      context: ./server
    container_name: tiktokmonitor-server
    restart: unless-stopped
    ports:
      - "8099:8099"
    volumes:
      - type: bind
        source: ./server/config.yaml
        target: /app/config.yaml
        read_only: true
      - ./backups:/app/backups
      - tiktokmonitor-data:/app/data

volumes:
  tiktokmonitor-data:
